parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'cypress'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:cypress/recommended'
rules:
  'no-empty': 0
  'react/react-in-jsx-scope': 0
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-empty-interface': 0
  '@typescript-eslint/no-use-before-define': 0
  '@typescript-eslint/camelcase': 0
  '@typescript-eslint/no-non-null-assertion': 0
  '@typescript-eslint/no-unused-vars': 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
env:
  'node': true
  'cypress/globals': true
