projects:
  frontend:
    schema: 'packages/aiacta-graphql/graphql/**/*.gql'
    documents: 'packages/aiacta-frontend/src/**/*.{gql,graphql,ts,tsx}'
    extensions:
      endpoints:
        default:
          url: 'http://localhost:8080'
          headers:
            # Authorization: `Bearer ${process.env.API_TOKEN}`
