packageExtensions:
  '@rsuite/icon-font@*':
    dependencies:
      react: '*'
  '@rsuite/icons@*':
    dependencies:
      '@babel/runtime': '*'
      prop-types: '*'
  dom-lib@*:
    dependencies:
      '@babel/runtime': '*'
  rsuite-table@*:
    dependencies:
      prop-types: '*'
  '@fullhuman/postcss-purgecss@*':
    dependencies:
      postcss: '*'
  'troika-three-text@*':
    dependencies:
      three: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-2.4.1.cjs
