name: Release

on:
  push:
    tags: ['v*']

jobs:
  tagged-release:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: 'Validate'
        run: yarn install --immutable --immutable-cache
      - name: 'Test'
        run: yarn test
      - name: 'Constraints'
        run: yarn constraints
      - name: 'Build'
        run: yarn build
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            LICENSE.md
            dist/**/*
